# Generated by Django 3.1.4 on 2022-01-20 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 1, 20, 11, 13, 29, 117890, tzinfo=utc), max_length=19),
        ),
    ]
