# Generated by Django 3.1.4 on 2022-01-23 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20220120_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 1, 23, 14, 25, 4, 942964, tzinfo=utc), max_length=19),
        ),
    ]
